### ISSUE TITLE
Support for expo 31.0.0 / react 16.5.0

### ISSUE THREAD

**Issue by MucyoMurenzi** [ambistudio/react-native-onboarding-animate#1]
Used this in my expo project at expo 30.0.0 and worked fine but when I upgraded to expo 31.0.0 which uses React Native v0.57.1 I received the following error

`undefined is not an object (evaluating '_reactNative.View.propTypes.style')`

After messing around a bit I was able to get it working by changing line 322 in OnboardingAnimate.js from

`  sceneContainerStyle: View.propTypes.style, `
to 
` sceneContainerStyle: PropTypes.style,`

It works fine now but I'm wondering if this fix could be implemented to prevent others from digging around in node_modules for ages to fix the problem?

**Comment by hieunc229** [comment]
Thank you for reporting this issue. I realised `View.propTypes.style` has been removed awhile ago (https://github.com/facebook/react-native/issues/16542#issuecomment-339530889).

I'll push an update for this issue.

**Comment by hieunc229** [comment]
I have pushed an update and tested on the actual. Thanks again for reporting the issue!

**Comment by MucyoMurenzi** [comment]
My bad, turns out this way still gives a warning. 

According to this https://stackoverflow.com/a/47629818/11037880
`react-native` has a `ViewPropTypes` to use in place of the old `View.propTypes`
I've tested it and it works fine with no warnings. If you'd like I can make a PR with these changes

Edit: I haven't tested it on versions of expo < 31 or react native < 0.57.0

**Comment by hieunc229** [comment]
Thanks for the info. I’d appreciate if you make a PR!

_(My bad I didn’t notice the warning message)_

**Comment by MucyoMurenzi** [comment]
I can't push my changes to a new branch, I'm getting a permission denied error

**Comment by hieunc229** [comment]
You might need to [create a PR from folk](https://help.github.com/articles/creating-a-pull-request-from-a-fork/).

I'll update and publish to NPM.

**Comment by MucyoMurenzi** [comment]
Yeah that worked, I'm happy to close this now. Thanks for the help :smile:

**Comment by hieunc229** [comment]
I have published the update into NPM (version 1.1.0)
Thank for the PR!
