### ISSUE TITLE
Support Expo 4x

### ISSUE THREAD

**Issue by hieunc229** [ambistudio/react-native-onboarding-animate#5]
Hello,

are you willing to update this package?? whenever i run it on Expo 40, i got ComponentWillMount is renamed and animated.event requires a second parameter
Thanks

_Originally posted by @elie-chaaban in https://github.com/ambistudio/react-native-onboarding-animate/issues/3#issuecomment-762864043_

**Comment by hieunc229** [comment]
Hi @elie-chaaban, I've pushed a new version (which also rewrite to typescript). I haven't been working with Expo for awhile and having trouble testing the library.

Can you test the new version (v1.2.1) and let me know if there is any problem?
Thank you!

**Comment by hieunc229** [comment]
I managed to update the library, test it on an iPhone. It should be working now. Also check out the [Onboarding Animation snack on Expo](https://snack.expo.io/@hieunc/on-boarding-animation)

I'll go ahead and close this issue. Feel free to re-open or create a new one.

**Comment by elie-chaaban** [comment]
Perfect
